services:
  php:
    image: easy-php:7.4
    networks:
      - local_public
    ports:
      - "59501:9501"
    volumes:
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
#Docker Networks
networks:
  local_public:
    external: true